const THREE_CARD_DRAW = 'THREE CARD DRAW'
const DRAW_ANYTHING = 'DRAW ANYTHING'
const SINGLE_CARD_ONLY = 'SINGLE CARD ONLY'
const PAIR_CARD_ONLY = 'PAIR CARD ONLY'

export { THREE_CARD_DRAW, DRAW_ANYTHING, SINGLE_CARD_ONLY, PAIR_CARD_ONLY }
