const THREE_CARD_DRAW = 'DRAW 3'
const DRAW_ANYTHING = 'DRAW ANYTHING'
const SINGLE_CARD_ONLY = 'SINGLE CARD ONLY'
const PAIR_CARD_ONLY = 'PAIR CARD ONLY'
const TRIPLE_CARD_ONLY = 'TRIPLE CARD ONLY'
const FIVE_CARD_ONLY = 'FIVE CARD ONLY'
// const STRAIGHT_ONLY = 'STRAIGHT ONLY'
// const FLUSH_ONLY = 'FLUSH ONLY'
// const FULL_HOUSE_ONLY = 'FULL_HOUSE ONLY'
// const FOUR_OF_KIND_ONLY = 'FOUR OF KIND ONLY'
// const STRAIGHT_FLUSH_ONLY = 'STRAIGHT FLUSH ONLY'

// export { THREE_CARD_DRAW, DRAW_ANYTHING, SINGLE_CARD_ONLY, PAIR_CARD_ONLY, 
//     TRIPLE_CARD_ONLY, STRAIGHT_ONLY, FLUSH_ONLY, FULL_HOUSE_ONLY, FOUR_OF_KIND_ONLY,
//     STRAIGHT_FLUSH_ONLY }

export { THREE_CARD_DRAW, DRAW_ANYTHING, SINGLE_CARD_ONLY, PAIR_CARD_ONLY, 
    TRIPLE_CARD_ONLY, FIVE_CARD_ONLY }
